services:
  sv:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISABLE_FLASH_INFER=yes
      - CONCURRENCY_PER_WORKER=1