services:
  sv:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: degroote22/lmscript-runpod-serverless-vllm:0.0.1
    command: python3 -u /src/handler.py --rp_serve_api --rp_api_host='0.0.0.0'
    network_mode: host
    volumes:
      - runpod:/runpod-volume
volumes:
  runpod: