name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41.2
      - run: npm config set "@tiptap-pro:registry" https://registry.tiptap.dev/
      - run: npm config set "@jsr:registry" https://npm.jsr.io
      - run: npm config set "//registry.tiptap.dev/:_authToken" ${{ secrets.TIPTAP_TOKEN }}
      - run: pnpm i
      - run: pnpm run static
      - run: pnpm run build
