name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41.2
      - run: cd client && deno fmt --check
      - run: cd client && deno lint
      - run: cd client && deno check src/**/*.ts
      - run: npm config set "@tiptap-pro:registry" https://registry.tiptap.dev/
      - run: npm config set "@jsr:registry" https://npm.jsr.io
      - run: npm config set "//registry.tiptap.dev/:_authToken" ${{ secrets.TIPTAP_TOKEN }}
      - run: cd gui && npm ci && npm run static
      - run: cd gui && npm ci && npm run test -- --run
